services:
  app:
    image: todo-front
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
      - 3000:80
    container_name: todo-front # This will name the container hello-front-dev
